# https://taskfile.dev

version: '3'

tasks:
  dev:
    cmds:
      - cd {{.DIRECTORY}}/client && npm run dev
    silent: false
  install:
    cmds:
      - cd {{.DIRECTORY}}/client && npm install
    silent: false
