# https://taskfile.dev

version: '3'

vars:
  DIRECTORY: {sh: pwd}

includes:
  api:
    taskfile: ./api/Taskfile.yaml
  client:
    taskfile: ./client/Taskfile.yaml

tasks:
  dev:
    cmds:
      - task: api:dev
      - task: client:dev
  install:
    cmds:
      - task: api:install
      - task: client:install
  setup:
    cmds:
      - task: api:setup
      - task: client:install
  test:
    cmds:
      - task: api:test
#      - task: client:test
