#!/bin/sh
CLIENT_FILES=$(git diff --cached --name-only --diff-filter=ACMR client | sed 's| |\\ |g')

# Prettify all selected files
echo "$CLIENT_FILES" | xargs ./client/node_modules/.bin/prettier --ignore-unknown --write

echo $(pwd);

pushd api

xargs ./vendor/bin/sail composer format

popd

git add .

exit 0
