# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, api!

tasks:
  dev:
    cmds:
      - cd {{.DIRECTORY}}/api && vendor/bin/sail up -d
    silent: false
  install:
    cmds:
      - |
        cd {{.DIRECTORY}}/api && \
        docker run --rm \
        -u "$(id -u):$(id -g)" \
        -v $(pwd):/var/www/html \
        -w /var/www/html \
        laravelsail/php81-composer:latest \
        composer install --ignore-platform-reqs
    silent: false
