# https://taskfile.dev

version: '3'

vars:
  SAIL: vendor/bin/sail

tasks:
  dev:
    cmds:
      - cd {{.DIRECTORY}}/api && {{.SAIL}} up -d
    silent: false
  format:
    cmds:
      - cd {{.DIRECTORY}}/api && {{.SAIL}} composer format
    silent: false
  install:
    cmds:
      - |
        cd {{.DIRECTORY}}/api && \
        docker run --rm \
        -u "$(id -u):$(id -g)" \
        -v $(pwd):/var/www/html \
        -w /var/www/html \
        laravelsail/php81-composer:latest \
        composer install --ignore-platform-reqs
    silent: false
  lint:
    cmds:
      - cd {{.DIRECTORY}}/api && {{.SAIL}} composer lint
    silent: false
  migrate:
    cmds:
      - cd {{.DIRECTORY}}/api && {{.SAIL}} artisan migrate:fresh
  seed:
    cmds:
      - cd {{.DIRECTORY}}/api && {{.SAIL}} artisan db:seed
  setup:
    cmds:
      - task: install
      - task: dev
      - task: migrate
      - task: seed
    silent: false
  test:
    cmds:
      - cd {{.DIRECTORY}}/api && {{.SAIL}} composer test
    silent: false
